import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import type { Activity } from '../../models/activity'
import { activityRepository } from '../../repositories/local/repositories'
import { csv, EditorActions, Field, join, slugPattern, TextAreaField, type Errors } from './EditorFields'

const empty:Activity={id:'',title:'',slug:'',date:'',type:'',summary:'',description:'',tags:[],featured:false,coverImage:{alt:'',variant:'a'},gallery:[],relatedMathematics:[],relatedPublications:[],status:'draft',createdAt:'',updatedAt:''}
export function ActivityEditorPage(){const {id}=useParams();const navigate=useNavigate();const [form,setForm]=useState(empty);const [errors,setErrors]=useState<Errors>({});const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false)
useEffect(()=>{if(id)activityRepository.getById(id).then(record=>record?setForm(record):navigate('/admin/activities'))},[id,navigate]);useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault()};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
const set=<K extends keyof Activity>(key:K,value:Activity[K])=>{setForm(current=>({...current,[key]:value}));setDirty(true)}
async function validate(){const next:Errors={};if(!form.title.trim())next.title='Enter a title.';if(!form.slug.trim())next.slug='Enter a slug.';else if(!slugPattern.test(form.slug))next.slug='Use lowercase letters, numbers, and single hyphens only.';if(!form.date)next.date='Choose a date.';if(!form.type.trim())next.type='Enter an activity type.';if((await activityRepository.listAll()).some(record=>record.slug===form.slug&&record.id!==form.id))next.slug='This activity slug is already in use.';setErrors(next);return !Object.keys(next).length}
async function save(){if(!await validate())return null;setSaving(true);try{const values={...form};let record;if(form.id)record=await activityRepository.update(form.id,values);else {const {id:_,status:__,createdAt:___,updatedAt:____,...input}=values;void _;void __;void ___;void ____;record=await activityRepository.create(input)}setForm(record);setDirty(false);if(!id)navigate(`/admin/activities/${record.id}/edit`,{replace:true});return record}finally{setSaving(false)}}
async function publish(){const record=await save();if(record&&window.confirm(`Publish “${record.title}” to the public website?`)){setForm(await activityRepository.publish(record.id));setDirty(false)}}async function unpublish(){if(window.confirm(`Unpublish “${form.title}”? It will remain available here.`)){setForm(await activityRepository.unpublish(form.id));setDirty(false)}}
return <Editor title={form.id?'Edit Activity':'New Activity'} status={form.status}><div className="admin-form-grid"><Field label="Title" name="title" value={form.title} error={errors.title} required onChange={v=>set('title',v)}/><Field label="Slug" name="slug" value={form.slug} error={errors.slug} required onChange={v=>set('slug',v)}/><Field label="Date" name="date" type="date" value={form.date} error={errors.date} required onChange={v=>set('date',v)}/><Field label="Type" name="type" value={form.type} error={errors.type} required onChange={v=>set('type',v)}/></div><TextAreaField label="Summary" name="summary" value={form.summary} onChange={v=>set('summary',v)}/><TextAreaField label="Description" name="description" rows={8} value={form.description} onChange={v=>set('description',v)}/><div className="admin-form-grid"><Field label="Tags (comma separated)" name="tags" value={join(form.tags)} onChange={v=>set('tags',csv(v))}/><Field label="Cover image alt text (placeholder)" name="cover-alt" value={form.coverImage.alt} onChange={v=>set('coverImage',{...form.coverImage,alt:v})}/><Field label="Related Mathematics IDs" name="related-mathematics" value={join(form.relatedMathematics)} onChange={v=>set('relatedMathematics',csv(v))}/><Field label="Related Publication IDs" name="related-publications" value={join(form.relatedPublications)} onChange={v=>set('relatedPublications',csv(v))}/></div><label className="admin-check"><input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)}/> Feature on public home page</label><p className="media-placeholder">Cover media is metadata-only in Stage 4. No file will be uploaded.</p><EditorActions status={form.status} saving={saving} onSave={()=>void save()} onPublish={()=>void publish()} onUnpublish={()=>void unpublish()}/></Editor>}
function Editor({title,status,children}:{title:string;status:string;children:React.ReactNode}){return <div className="admin-page editor-page"><header className="admin-page-head"><Link className="back-link" to="/admin/activities">← Activities</Link><div className="editor-title"><div><p className="eyebrow">Activity editor</p><h1>{title}</h1></div><span className={`status status-${status}`}>{status}</span></div></header><form onSubmit={e=>e.preventDefault()}>{children}</form></div>}
