import { useEffect, useState, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { MarkdownRenderer } from '../../components/content/MarkdownRenderer'
import type { Mathematics } from '../../models/mathematics'
import { mathematicsRepository } from '../../repositories/local/repositories'
import { csv, EditorActions, Field, join, slugPattern, TextAreaField, type Errors } from './EditorFields'

const empty:Mathematics={id:'',title:'',slug:'',authors:[],field:'',type:'',year:new Date().getFullYear(),summary:'',tags:[],relatedActivities:[],relatedPublications:[],relatedMathematics:[],status:'draft',content:'# New mathematics article\n\nWrite the article in Markdown. Inline math: \\(G\\).\n\n$$\nn_p \\equiv 1 \\pmod p\n$$',coverImage:{alt:'',variant:'blue'},attachments:[],createdAt:'',updatedAt:''}
export function MathematicsEditorPage(){const {id}=useParams();const navigate=useNavigate();const [form,setForm]=useState(empty);const [errors,setErrors]=useState<Errors>({});const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false)
useEffect(()=>{if(id)mathematicsRepository.getById(id).then(record=>record?setForm(record):navigate('/admin/mathematics'))},[id,navigate]);useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault()};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);const set=<K extends keyof Mathematics>(key:K,value:Mathematics[K])=>{setForm(current=>({...current,[key]:value}));setDirty(true)}
async function validate(){const next:Errors={};if(!form.title.trim())next.title='Enter a title.';if(!form.slug.trim())next.slug='Enter a slug.';else if(!slugPattern.test(form.slug))next.slug='Use lowercase letters, numbers, and single hyphens only.';if(!form.year||form.year<1900)next.year='Enter a valid year.';if(!form.type.trim())next.type='Enter a resource type.';if(!form.field.trim())next.field='Enter a mathematics field.';if((await mathematicsRepository.listAll()).some(record=>record.slug===form.slug&&record.id!==form.id))next.slug='This mathematics slug is already in use.';setErrors(next);return !Object.keys(next).length}
async function save(){if(!await validate())return null;setSaving(true);try{const values={...form};let record;if(form.id)record=await mathematicsRepository.update(form.id,values);else {const {id:_,status:__,createdAt:___,updatedAt:____,...input}=values;void _;void __;void ___;void ____;record=await mathematicsRepository.create(input)}setForm(record);setDirty(false);if(!id)navigate(`/admin/mathematics/${record.id}/edit`,{replace:true});return record}finally{setSaving(false)}}
async function publish(){const record=await save();if(record&&window.confirm(`Publish “${record.title}” to the public mathematics archive?`)){setForm(await mathematicsRepository.publish(record.id));setDirty(false)}}async function unpublish(){if(window.confirm(`Unpublish “${form.title}”? It will remain available here.`)){setForm(await mathematicsRepository.unpublish(form.id));setDirty(false)}}
return <Editor title={form.id?'Edit Mathematics':'New Mathematics'} status={form.status}><div className="admin-form-grid"><Field label="Title" name="title" value={form.title} error={errors.title} required onChange={v=>set('title',v)}/><Field label="Slug" name="slug" value={form.slug} error={errors.slug} required onChange={v=>set('slug',v)}/><Field label="Authors (comma separated)" name="authors" value={join(form.authors)} onChange={v=>set('authors',csv(v))}/><Field label="Year" name="year" type="number" value={form.year} error={errors.year} required onChange={v=>set('year',Number(v))}/><Field label="Field" name="field" value={form.field} error={errors.field} required onChange={v=>set('field',v)}/><Field label="Type" name="type" value={form.type} error={errors.type} required onChange={v=>set('type',v)}/></div><TextAreaField label="Summary" name="summary" value={form.summary} onChange={v=>set('summary',v)}/><div className="admin-form-grid"><Field label="Tags (comma separated)" name="tags" value={join(form.tags)} onChange={v=>set('tags',csv(v))}/><Field label="Related Activity IDs" name="activities" value={join(form.relatedActivities)} onChange={v=>set('relatedActivities',csv(v))}/><Field label="Related Publication IDs" name="publications" value={join(form.relatedPublications)} onChange={v=>set('relatedPublications',csv(v))}/><Field label="Cover image alt text (placeholder)" name="cover-alt" value={form.coverImage.alt} onChange={v=>set('coverImage',{...form.coverImage,alt:v})}/></div><section className="markdown-editor"><div><TextAreaField label="Markdown content" name="content" rows={24} value={form.content} onChange={v=>set('content',v)}/><p className="field-help">Supports headings, paragraphs, lists, links, fenced code, inline math with \(…\), and display math with $$…$$. Stored HTML is sanitized.</p></div><div className="markdown-preview"><span className="field-label">Preview</span><MarkdownRenderer content={form.content}/></div></section><EditorActions status={form.status} saving={saving} onSave={()=>void save()} onPublish={()=>void publish()} onUnpublish={()=>void unpublish()}/></Editor>}
function Editor({title,status,children}:{title:string;status:string;children:ReactNode}){return <div className="admin-page editor-page"><header className="admin-page-head"><Link className="back-link" to="/admin/mathematics">← Mathematics</Link><div className="editor-title"><div><p className="eyebrow">Mathematics editor</p><h1>{title}</h1></div><span className={`status status-${status}`}>{status}</span></div></header><form onSubmit={e=>e.preventDefault()}>{children}</form></div>}
