import { useEffect, useState, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import type { Publication } from '../../models/publication'
import { publicationRepository } from '../../repositories/local/repositories'
import { csv, EditorActions, Field, join, slugPattern, TextAreaField, type Errors } from './EditorFields'

const empty:Publication={id:'',title:'',slug:'',year:new Date().getFullYear(),type:'',summary:'',description:'',authors:[],editors:[],coverImage:{alt:'',variant:'light'},relatedActivities:[],relatedMathematics:[],status:'draft',createdAt:'',updatedAt:''}
export function PublicationEditorPage(){const {id}=useParams();const navigate=useNavigate();const [form,setForm]=useState(empty);const [errors,setErrors]=useState<Errors>({});const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false)
useEffect(()=>{if(id)publicationRepository.getById(id).then(record=>record?setForm(record):navigate('/admin/publications'))},[id,navigate]);useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty)event.preventDefault()};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);const set=<K extends keyof Publication>(key:K,value:Publication[K])=>{setForm(current=>({...current,[key]:value}));setDirty(true)}
async function validate(){const next:Errors={};if(!form.title.trim())next.title='Enter a title.';if(!form.slug.trim())next.slug='Enter a slug.';else if(!slugPattern.test(form.slug))next.slug='Use lowercase letters, numbers, and single hyphens only.';if(!form.year||form.year<1900)next.year='Enter a valid year.';if(!form.type.trim())next.type='Enter a publication type.';if((await publicationRepository.listAll()).some(record=>record.slug===form.slug&&record.id!==form.id))next.slug='This publication slug is already in use.';setErrors(next);return !Object.keys(next).length}
async function save(){if(!await validate())return null;setSaving(true);try{const values={...form};let record;if(form.id)record=await publicationRepository.update(form.id,values);else {const {id:_,status:__,createdAt:___,updatedAt:____,...input}=values;void _;void __;void ___;void ____;record=await publicationRepository.create(input)}setForm(record);setDirty(false);if(!id)navigate(`/admin/publications/${record.id}/edit`,{replace:true});return record}finally{setSaving(false)}}
async function publish(){const record=await save();if(record&&window.confirm(`Publish “${record.title}” to the public publications archive?`)){setForm(await publicationRepository.publish(record.id));setDirty(false)}}async function unpublish(){if(window.confirm(`Unpublish “${form.title}”? It will remain available here.`)){setForm(await publicationRepository.unpublish(form.id));setDirty(false)}}
return <Editor title={form.id?'Edit Publication':'New Publication'} status={form.status}><div className="admin-form-grid"><Field label="Title" name="title" value={form.title} error={errors.title} required onChange={v=>set('title',v)}/><Field label="Slug" name="slug" value={form.slug} error={errors.slug} required onChange={v=>set('slug',v)}/><Field label="Year" name="year" type="number" value={form.year} error={errors.year} required onChange={v=>set('year',Number(v))}/><Field label="Type" name="type" value={form.type} error={errors.type} required onChange={v=>set('type',v)}/><Field label="Authors (comma separated)" name="authors" value={join(form.authors)} onChange={v=>set('authors',csv(v))}/><Field label="Editors (comma separated)" name="editors" value={join(form.editors)} onChange={v=>set('editors',csv(v))}/></div><TextAreaField label="Summary" name="summary" value={form.summary} onChange={v=>set('summary',v)}/><TextAreaField label="Description" name="description" rows={8} value={form.description} onChange={v=>set('description',v)}/><div className="admin-form-grid"><Field label="Cover image alt text (placeholder)" name="cover-alt" value={form.coverImage.alt} onChange={v=>set('coverImage',{...form.coverImage,alt:v})}/><Field label="Related Activity IDs" name="activities" value={join(form.relatedActivities)} onChange={v=>set('relatedActivities',csv(v))}/><Field label="Related Mathematics IDs" name="mathematics" value={join(form.relatedMathematics)} onChange={v=>set('relatedMathematics',csv(v))}/><Field label="PDF file name (placeholder)" name="pdf-name" value={form.pdf?.fileName??''} onChange={v=>set('pdf',v?{label:form.pdf?.label??'PDF',fileName:v,mediaType:'application/pdf',sizeLabel:form.pdf?.sizeLabel??'PDF · placeholder'}:undefined)}/></div><p className="media-placeholder">Cover and PDF controls store metadata only. No files are uploaded in Stage 4.</p><EditorActions status={form.status} saving={saving} onSave={()=>void save()} onPublish={()=>void publish()} onUnpublish={()=>void unpublish()}/></Editor>}
function Editor({title,status,children}:{title:string;status:string;children:ReactNode}){return <div className="admin-page editor-page"><header className="admin-page-head"><Link className="back-link" to="/admin/publications">← Publications</Link><div className="editor-title"><div><p className="eyebrow">Publication editor</p><h1>{title}</h1></div><span className={`status status-${status}`}>{status}</span></div></header><form onSubmit={e=>e.preventDefault()}>{children}</form></div>}
